### PR TITLE
Fix for namespace not being the url from the modelInfo in _typeHierarchy

### PR DESCRIPTION
**Pull request by hossenlopp**
Fixes namespace not being the url in the results from the _typeHierarchy function.

### CODE REVIEW

**Review by okeefm — APPROVED** [review]
Tested these changes by copying the `_is` and `_typeHierarchy` tests into r401_test from r4_test. They failed on the `is_operator` branch, but passed here. Looks good!

**Review by cmoesel — APPROVED** [review]
I decided we should probably just round things out by adding the DSTU2 and STU3 tests.  Which is good, because the DSTU2 ones failed -- requiring one more tweak to the code.

As a bonus, I updated dependencies to resolve vulnerabilities reported by GitHub and yarn audit.  If you don't want those in this PR, we can back them out.

Looking for an additional approval since I made changes.

**Comment by cmoesel** [comment]
OK, so it turns out that the upgraded eslint requires Node 10, and travis was using Node 8.  So I bumped Travis to Node 10.  I think Node 10 is a reasonable requirement.  Again, feel free to disagree.

**Comment by okeefm** [comment]
> I think Node 10 is a reasonable requirement.

Agreed

**Review by okeefm — APPROVED** [review]
Changes make sense to me; tests all pass. Thanks for going ahead and moving all the tests to all the test suites!

**Comment by cmoesel** [comment]
OK.  Since this is just going into another branch (not master) anyway, I think we're good to merge this!

**Pull request merged**
