### PR TITLE
Upgrading dependencies to resolve security vulnerabilities

### PR DESCRIPTION
**Pull request by AndrewBird81**
These security vulnerabilities are blocking some of our Bonnie on FHIR development work. Ideally these changes would constitute a release of version 2.0.1.

### CODE REVIEW

**Review by cmoesel — CHANGES_REQUESTED** [review]
The CI build is failing because eslint 8.x requires Node 12 -- and CI is configured to use Node 10.  There are two potential ways to fix this:
- Revert eslint back to latest 7.x release (although I don't know if that would reintroduce any vulnerabilities), OR
- Update `.travis.yml` to use Node 12 instead of Node 10

Can you push up a commit with one of those fixes?

Since `cql-execution` is on Node 12 already, I'm not opposed to bumping this one to 12 as well -- so that's probably the better approach right now.

**Comment by AndrewBird81** [comment]
Ah yes, good catch. Node 10 has passed its end of life, so I don't think dropping support for it is controversial. 

On other projects we've migrated away from Travis CI in favor of GitHub Actions. Would you like me to add that transition while I'm here?

**Comment by cmoesel** [comment]
Yeah, we use GitHub Actions on `cql-execution`.  I guess we just never got around to converting it over here.  I'm glad to use GitHub Actions for `cql-exec-fhir` -- but it's up to you if you want to do that work for this PR.  It's obviously outside the scope of the PR.  So... in short... I'll gladly accept the PR with or without the conversion to GitHub Actions.  It is up to you.

**Comment by AndrewBird81** [comment]
I'm not sure how I missed this, but the new version of `chai` did not like this syntax:
`expect(paymentReconciliations.length).to.be.empty;`

So I corrected it (in several places) to:
`expect(paymentReconciliations).to.be.empty;`

Also, I added a GitHub action, but it is difficult to test without checking it in and trying it out 🤞

**Comment by cmoesel** [comment]
Yikes.  Thanks for making that fix to the unit tests.  It definitely makes more sense _without_ the `.length`.  Let me see if I can figure out how to get that GitHub action CI to trigger on this branch.

**Comment by cmoesel** [comment]
Still trying to figure that out, but I think you will also need to delete the travis config file (or also update it to use 12).

**Comment by cmoesel** [comment]
It looks like that did it! (And I figured out how to get the actions running as part of the CI).  I'd still like to do some additional testing on it, so I'll aim to get it done early next week.

**Review by cmoesel — APPROVED** [review]
Thanks for doing this, @AndrewBird81.  I've reviewed it and it all looks good.  I've also confirmed that it still works w/ existing FHIR-based CQL and tests.

**Pull request merged**
